### ISSUE TITLE
Folder structure

### ISSUE THREAD

**Issue by cristeacosmin** [MachoThemes/uber-recaptcha#7]
Daca tot ii facem update la plugin, hai sa mutam si fisierele sa aiba sens

- [x] css in assets/css

- [x] js in assets/js

- [x] helpers puse in includes

- [ ] hai sa modificam si numele fisierelor according to WP Coding Standards https://make.wordpress.org/core/handbook/best-practices/coding-standards/php/#naming-conventions

**Comment by razvanaldea89** [comment]
This is fixed
